NumPy Arrays

In [2]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [7]:
arr=np.array(my_list)

In [8]:
arr

array([1, 2, 3])

In [9]:
my_mat = [[1,2,3],[4,5,6,],[7,8,9]]

In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.random.rand(5)

array([0.21280039, 0.32097816, 0.02415375, 0.48161171, 0.74271911])

In [25]:
np.random.rand(5,5)

array([[0.23264223, 0.53437028, 0.7337173 , 0.28822605, 0.09261098],
       [0.26362904, 0.61133625, 0.70150118, 0.03508744, 0.14799951],
       [0.84575517, 0.37959125, 0.79706357, 0.13521934, 0.22262107],
       [0.74303115, 0.64352786, 0.9211778 , 0.69187965, 0.48614992],
       [0.59811218, 0.94557976, 0.40822997, 0.64629248, 0.21897315]])

In [27]:
np.random.randn(2,2)

array([[-1.53448666,  0.41863056],
       [ 0.36139467,  1.4683876 ]])

In [30]:
np.random.randint(1,100,10)

array([87, 14, 73, 45, 46, 27, 83, 91, 26, 65])

In [32]:
arr = np.arange(25)

In [41]:
ranarr = np.random.randint(4,50,10)

In [42]:
ranarr

array([36,  6,  5, 35, 10, 46, 13, 45, 38, 45])

In [40]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
ranarr.min()

5

In [44]:
ranarr

array([36,  6,  5, 35, 10, 46, 13, 45, 38, 45])

In [45]:
ranarr.argmax()

5

In [46]:
ranarr.argmin()

2

In [47]:
arr.shape

(25,)

In [48]:
arr = arr.reshape(5,5)

In [49]:
arr.shape

(5, 5)

In [50]:
arr.dtype

dtype('int64')

In [51]:
from numpy.random import randint

In [52]:
randint(2,10)

7